### PR TITLE
Bump base's upper bound to 5

### PR DESCRIPTION
**Pull request by Kleidukos**
I would like to submit an upper bound bump on base in the context of preparing Haddock for GHC 9.2.

### CODE REVIEW

**Comment by phadej** [comment]
Sorry. I won't do this ever.

**Comment by phadej** [comment]
And if you want a concrete reason:

```
src/Data/TreeDiff/Class.hs:instance ToExpr a => ToExpr (Semi.Option a) where
src/Data/TreeDiff/Class.hs:    toExpr (Semi.Option x) = App "Option" [toExpr x]
```

`Option` is one in 9.2. And changes like that may happen in every major `base` release. I **won't** bump base upper bound to `base <5` in any packages I maintain (and will introduce stricter ones in e.g. `aeson` etc.).

**Comment by Kleidukos** [comment]
@phadej Could you then maybe relax the upper bound to include 4.16? Or is that out of the question as well?

**Comment by phadej** [comment]
How `haddock` test-suite would work. E.g. `tree-diff` depends on `aeson` and `hashable` which I know for sure don't work with GHC-9.2, i.e. you are probably using `head.hackage`. Why not submit a patch for `tree-diff` to `head.hackage`?

**Comment by Kleidukos** [comment]
I'm just following cabal's complaints in terms of bounds (and I'd appreciate a lot if you could unlock base-4.16 for `hashable`)

**Comment by Kleidukos** [comment]
@phadej and no I'm not using head.hackage

**Pull request closed without merging**
